export const projectId = "kdnsfwbyoaojcyqbxsvc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkbnNmd2J5b2FvamN5cWJ4c3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNTM4OTgsImV4cCI6MjA4NzcyOTg5OH0.K-PyYIC1u-gHZOCZHXCMH5f3chdWhgCiCFamB48GvwM"
